# Generated by Django 6.0.6 on 2026-07-07 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='Número de Bloque')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('merkle_root', models.CharField(max_length=64, verbose_name='Raíz de Merkle')),
                ('previous_hash', models.CharField(max_length=64, verbose_name='Hash del Bloque Anterior')),
                ('block_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash del Bloque Actual')),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=50, unique=True, verbose_name='Código del Certificado')),
                ('nombre_alumno', models.CharField(max_length=150, verbose_name='Nombre del Alumno')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera Universitaria')),
                ('hash_certificado', models.CharField(max_length=64, unique=True, verbose_name='SHA-256 del Certificado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados', to='blockchain.bloquemodel')),
            ],
        ),
    ]
